parameters:
    translations.yaml: "%kernel.root_dir%/../src/WebBundle/Resources/i18n/translations.yml"

services:
    guzzle.client:
        class: GuzzleHttp\Client
    web.guzzle_request_handler:
        class: WebBundle\RequestHandler\Middleware\GuzzleRequestHandler
        arguments:
            - "@guzzle.client"
            - "@service_container"
    web.event_request_handler:
        class: WebBundle\RequestHandler\Middleware\EventRequestHandler
        arguments:
            - "@event_dispatcher"
            - "@web.guzzle_request_handler"
    web.locale_listener:
        class: WebBundle\EventListener\LocaleListener
        arguments:
            - '%kernel.default_locale%'
            - "@service_container"
        tags:
            - { name: kernel.event_subscriber }
    web.request_handler:
        alias: web.event_request_handler
    web.request_handler.json_response_listener:
        class: WebBundle\RequestHandler\Listener\JsonResponseListener
        tags:
            - { name: kernel.event_listener, event: request_handler.received_response, method: onReceivedResponse }
    web.page_gateway:
        class: WebBundle\Gateway\PageGateway
        arguments:
            - "@web.request_handler"
            - "%wp_api_url%"
    web.menu_gateway:
        class: WebBundle\Gateway\MenuGateway
        arguments:
            - "@web.request_handler"
            - "%wp_api_url%"
    web.status_gateway:
        class: WebBundle\Gateway\StatusGateway
        arguments:
            - "@web.request_handler"
    web.instagram_gateway:
        class: WebBundle\Gateway\InstagramGateway
    web.question_gateway:
        class: WebBundle\Gateway\QuestionGateway
        arguments:
            - "@web.request_handler"
            - "%wp_api_url%"
    web.translations_gateway:
        class: WebBundle\Gateway\TranslationsGateway
        arguments:
            - "@web.request_handler"
            - "%wp_api_url%"
    web.widget_gateway:
        class: WebBundle\Gateway\WidgetGateway
        arguments:
            - "@web.request_handler"
            - "%wp_api_url%"
    web.rss_gateway:
        class: WebBundle\Gateway\RssGateway
        arguments:
            - "@web.request_handler"
            - "%blog_url%"
    web.consumer_service:
        class: WebBundle\Service\ConsumerService
        arguments:
            - '@service_container'
            - '@request_stack'
            - '%translations.yaml%'
    web.utils_service:
        class: WebBundle\Service\UtilsService
        arguments:
            - '@service_container'
            - '@request_stack'
    web.twig_extension:
        class: WebBundle\Twig\CustomExtensions
        public: false
        tags:
            - { name: twig.extension }
        arguments: ["@request_stack"]
    web.aes_service:
        class: WebBundle\Service\AES128Encryptor
        